name: places
description: surf_michurin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  equatable: ^2.0.5
  dio: ^5.1.1
  image_picker: ^0.8.7+4
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  freezed_annotation: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
#  dart_code_metrics: ^2.5.0
  surf_lint_rules: ^1.3.0
  build_runner: ^2.3.3
  freezed: ^2.2.0
  mobx_codegen:


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  


  
